<a href="https://colab.research.google.com/github/HarikrishnanK9/HarikrishnanK9/blob/main/Credit_Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Credit Score Classification Dataset**

In [19]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/Credit Score Classification Dataset.csv")
df

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000.0,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000.0,Master's Degree,Married,2,Owned,High
2,35,Female,75000.0,Doctorate,Married,1,Owned,High
3,40,Male,125000.0,High School Diploma,Single,0,Owned,High
4,45,Female,100000.0,Bachelor's Degree,Married,3,Owned,High
...,...,...,...,...,...,...,...,...
159,29,Female,27500.0,High School Diploma,Single,0,Rented,Low
160,34,Male,47500.0,Associate's Degree,Single,0,Rented,Average
161,39,Female,62500.0,Bachelor's Degree,Married,2,Owned,High
162,44,Male,87500.0,Master's Degree,Single,0,Owned,High
163,49,Female,77500.0,Doctorate,Married,1,Owned,High

In [20]:
df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000.0,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000.0,Master's Degree,Married,2,Owned,High
2,35,Female,75000.0,Doctorate,Married,1,Owned,High
3,40,Male,125000.0,High School Diploma,Single,0,Owned,High
4,45,Female,100000.0,Bachelor's Degree,Married,3,Owned,High

In [21]:
df.tail()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
159,29,Female,27500.0,High School Diploma,Single,0,Rented,Low
160,34,Male,47500.0,Associate's Degree,Single,0,Rented,Average
161,39,Female,62500.0,Bachelor's Degree,Married,2,Owned,High
162,44,Male,87500.0,Master's Degree,Single,0,Owned,High
163,49,Female,77500.0,Doctorate,Married,1,Owned,High

In [69]:
df.columns

Index(['Age', 'Gender', 'Income', 'Education', 'Marital Status',
       'Number of Children', 'Home Ownership', 'Credit Score'],
      dtype='object')

In [70]:
df.dtypes

Age                     int64
Gender                 object
Income                float64
Education              object
Marital Status         object
Number of Children      int64
Home Ownership         object
Credit Score           object
dtype: object

In [22]:
df.describe

<bound method NDFrame.describe of      Age  Gender    Income            Education Marital Status  \
0     25  Female   50000.0    Bachelor's Degree         Single
1     30    Male  100000.0      Master's Degree        Married
2     35  Female   75000.0            Doctorate        Married
3     40    Male  125000.0  High School Diploma         Single
4     45  Female  100000.0    Bachelor's Degree        Married
..   ...     ...       ...                  ...            ...
159   29  Female   27500.0  High School Diploma         Single
160   34    Male   47500.0   Associate's Degree         Single
161   39  Female   62500.0    Bachelor's Degree        Married
162   44    Male   87500.0      Master's Degree         Single
163   49  Female   77500.0            Doctorate        Married

     Number of Children Home Ownership Credit Score
0                     0         Rented         High
1                     2          Owned         High
2                     1          Owned         High
3                     0          Owned         High
4                     3          Owned         High
..                  ...            ...          ...
159                   0         Rented          Low
160                   0         Rented      Average
161                   2          Owned         High
162                   0          Owned         High
163                   1          Owned         High

[164 rows x 8 columns]>

In [23]:
df.isna().sum()

Age                   0
Gender                6
Income                9
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [34]:
df1=df.drop(["Gender"],axis=1)
df1

,Age,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,50000.0,Bachelor's Degree,Single,0,Rented,High
1,30,100000.0,Master's Degree,Married,2,Owned,High
2,35,75000.0,Doctorate,Married,1,Owned,High
3,40,125000.0,High School Diploma,Single,0,Owned,High
4,45,100000.0,Bachelor's Degree,Married,3,Owned,High
...,...,...,...,...,...,...,...
159,29,27500.0,High School Diploma,Single,0,Rented,Low
160,34,47500.0,Associate's Degree,Single,0,Rented,Average
161,39,62500.0,Bachelor's Degree,Married,2,Owned,High
162,44,87500.0,Master's Degree,Single,0,Owned,High
163,49,77500.0,Doctorate,Married,1,Owned,High

In [35]:
df1["Income"].fillna(df["Income"].mean(),inplace=True)

In [36]:
df1.isna().sum()

Age                   0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [37]:
df1.duplicated().sum()

58

In [44]:
df1.drop_duplicates()

,Age,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,50000.0,Bachelor's Degree,Single,0,Rented,High
1,30,100000.0,Master's Degree,Married,2,Owned,High
2,35,75000.0,Doctorate,Married,1,Owned,High
3,40,125000.0,High School Diploma,Single,0,Owned,High
4,45,100000.0,Bachelor's Degree,Married,3,Owned,High
...,...,...,...,...,...,...,...
130,31,95000.0,Doctorate,Single,0,Rented,High
131,26,55000.0,Bachelor's Degree,Married,1,Owned,Average
132,32,85000.0,Master's Degree,Single,0,Rented,High
133,29,68000.0,Doctorate,Married,2,Owned,Average
134,34,105000.0,Bachelor's Degree,Married,1,Rented,High

In [46]:
df1

,Age,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,50000.0,Bachelor's Degree,Single,0,Rented,High
1,30,100000.0,Master's Degree,Married,2,Owned,High
2,35,75000.0,Doctorate,Married,1,Owned,High
3,40,125000.0,High School Diploma,Single,0,Owned,High
4,45,100000.0,Bachelor's Degree,Married,3,Owned,High
...,...,...,...,...,...,...,...
159,29,27500.0,High School Diploma,Single,0,Rented,Low
160,34,47500.0,Associate's Degree,Single,0,Rented,Average
161,39,62500.0,Bachelor's Degree,Married,2,Owned,High
162,44,87500.0,Master's Degree,Single,0,Owned,High
163,49,77500.0,Doctorate,Married,1,Owned,High

In [58]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1['Education']=le.fit_transform(df1['Education'])
df1['Marital Status']=le.fit_transform(df1['Marital Status'])
df1['Home Ownership']=le.fit_transform(df1['Home Ownership'])
df1['Credit Score']=le.fit_transform(df1['Credit Score'])

In [59]:
x=df1.iloc[:,:-1].values
x

array([[2.50e+01, 5.00e+04, 1.00e+00, ..., 1.00e+00, 1.00e+00, 1.00e+00],
       [3.00e+01, 1.00e+05, 4.00e+00, ..., 0.00e+00, 1.00e+00, 1.00e+00],
       [3.50e+01, 7.50e+04, 2.00e+00, ..., 0.00e+00, 1.00e+00, 1.00e+00],
       ...,
       [3.90e+01, 6.25e+04, 1.00e+00, ..., 0.00e+00, 1.00e+00, 1.00e+00],
       [4.40e+01, 8.75e+04, 4.00e+00, ..., 0.00e+00, 1.00e+00, 1.00e+00],
       [4.90e+01, 7.75e+04, 2.00e+00, ..., 0.00e+00, 1.00e+00, 1.00e+00]])

In [60]:
y=df1.iloc[:,-1].values
y

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [63]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [65]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
knn=KNeighborsClassifier(n_neighbors=7)
base=GaussianNB()
model=SVC()
lst_model=[knn,base,model]

In [68]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
for i in lst_model:
  print(i)
  i.fit(x_train,y_train)
  y_pred=i.predict(x_test)
  print("********************************************************************************")
  print(classification_report(y_test,y_pred))
  print("********************************************************************************")
  print(confusion_matrix(y_test,y_pred))
  print("********************************************************************************")
  print(classification_report(y_test,y_pred))

KNeighborsClassifier(n_neighbors=7)
********************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        21

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

********************************************************************************
[[29  0]
 [ 0 21]]
********************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        21

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

GaussianNB()
********************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        21

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

********************************************************************************
[[29  0]
 [ 0 21]]
********************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        21

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

SVC()
********************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        21

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

********************************************************************************
[[29  0]
 [ 0 21]]
********************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        21

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50